improve dependency check workflow

diff --git a/.github/workflows/dependency-check.yml b/.github/workflows/dependency-check.yml
--- a/.github/workflows/dependency-check.yml
+++ b/.github/workflows/dependency-check.yml
@@ -9,15 +9,23 @@ jobs:
         uses: actions/checkout@v4
       - name: Node setup and install dependencies
         uses: ./.github/actions/setup-node/
-      - name: Check dependencies
+      - name: Run Dependency Check
         uses: dependency-check/Dependency-Check_Action@main
-        id: Depcheck
         with:
-          project: 'test'
           path: '.'
-          format: 'HTML'
-      - name: Upload Test results
-        uses: actions/upload-artifact@v4
+          project: 'cicd'
+          format: 'JSON'
+          out: './reports'
+      - name: Analyze Report for Critical Vulnerabilities
+        run: |
+          CRITICAL_COUNT=$(jq '[.dependencies[] | .vulnerabilities[] | select(.cvssScore >= 9.0)] | length' ./reports/dependency-check-report.json)
+          echo "Found $CRITICAL_COUNT critical vulnerabilities"
+          if [ "$CRITICAL_COUNT" -gt 0 ]; then
+            echo "Critical vulnerabilities found. Failing the pipeline."
+            exit 1
+          fi
+      - name: Upload report
+        uses: actions/upload-artifact@v3
         with:
-          name: Depcheck report
+          name: dependency-check-report
           path: ${{github.workspace}}/reports
